### ISSUE TITLE
バナー掲示再開につきまして

### ISSUE THREAD

**Issue by sksh-99** [Oliver-noah-Jacob/RandomBannerMu#27]
はじめまして。
なんでも実況Mu@おーぷぬ 元利用者です。訳あって捨てアカウントにて失礼します。
別の方のissueで「バナーの掲示再開」について言及されているようでしたので、一点お願いがあり投稿させていただきました。
大した内容ではありませんので、お暇なときに確認して頂ければ大丈夫です。

<以下 依頼内容>
別の方のissueで「バナーの掲示再開」について言及されているようですが、私の作成したバナーを除外して頂きたいです。
該当バナーの特徴は「海をモチーフとした青背景」「イメージキャラの"ムーさん"が描かれた黄色いムー大陸」「赤文字で"なんでも実況Mu @おーぷん2ch"」です。
バナー作成途中のデータが残っていましたので、証拠といっては何ですが、共有いたします。ご参考ください。
https://drive.google.com/drive/folders/17bJRwKF8oobaNV-01W8alN8m4fahjLSP?usp=sharing
「すぐにでも除外してほしい」というものではありませんので、お時間よろしいときにご対応頂ければと思います。

以上、お手数おかけしますがよろしくお願いいたします。

*追記 20230110_2100
すみません、バナースレのレス番号等記載しておりませんでしたので追記いたします。
レス番号 : >>82 および >>90
ID : XTCc

以上、よろしくお願いします。

**Comment by Oliver-noah-Jacob** [comment]
承知しました。
作者様だとお見受けしましたので、後ほど削除対応させていただきます。しばらくお待ちください。

追伸：私も捨てアカウントのようなものなのでお気になさらないでください。
（おーぷぬ関係の活動だけリアルgithubアカウントとは別にこのアカウントでやっているので）
